image: docker
services:
  - docker:dind 
stages:
  - build 
  - test  
docker-build:
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
gradle-build:
  script:
    - sh start.sh
