image: docker:dind
services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - main
  script: "./gradlew build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  only:
    - main
  script:
  - docker build -t $CI_REGISTRY_IMAGE .
