image: docker
services:
  - docker:dind 
stages:
  - build 
  - test  
docker-build:
  script:
    - apk add --no-cache docker-compose
    - export DEVELDIR=`pwd`
    - docker-compose up -d
    - docker-compose exec -T server bash
gradle-build:
  script:
    - sh build.sh

