stages:
  - build
  - test
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker-compose exec -T server sh cassandra.sh
    - sleep 60
    - docker-compose exec -T server sh loader.sh
    - docker-compose exec -T server sh build.sh
