image: docker:stable

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker-compose exct -T server sh cassandra.sh
    - docker-compose exec -t server sh loader.sh
    - docker-compose exec -T server sh build.sh


