image: docker:dind
services:
  - docker:dind

stages:
  - build
  - test

docker-build:
  stage: build
  only:
    - main
  script:
  - sh build.sh
  - sh start.sh
  - sh ssh.sh


gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - main
  script: 
  - "./gradlew build"
  - sh cassandra.sh
  - sh loader.sh
  - sh build.sh
  - sh exec.sh

  artifacts:
    paths:
      - build/libs/*.jar

