image: docker:stable

stages:
  - build
  - test

build:
  stage: test
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d

test:
  stage: test
  script:
    - docker-compose exec -T server ./gradlew test


