image: docker:stable

build:
  stage: build
  tags:
    - docker
  script:
    - apk add --no-cache docker-compose
    - export DEVELDIR=`pwd`
    - docker-compose build -d
    - docker-compose exec -T server bash
    - docker-compose run sh buil.sh



