image: docker:stable

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker-compose exec -T server bash
    - docker-compose exec sh build.sh


