image: docker
services:
  - docker:dind 
stages:
  - build 
  - test  
docker-build:
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker-compose exec server bash

