name: GitHubActions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: echo "hello world"
